name: Docker Build 

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-deploy:
     runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install 

      - name: build node modules
        run: npm install

      - name: Build Docker Image
        run: sudo docker build -t app .
        
      - name: Log in to Docker Hub
        run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag app vivekshaurya/thesocialedge-authservice
        

      - name: Push Docker Image
        run: docker push vivekshaurya/thesocialedge-authservice
